### PR TITLE
Try to fit the weekly Hydra update into this way of a report

### PR DESCRIPTION
**Pull request by ch1bo**
Any feedback on how to structure the content or how to align our weekly digest with the aim of this website welcome.

### CODE REVIEW

**Review by JaredCorduan — APPROVED** [review]
It looks great to me! The high level summary is the only structure that we've agreed each team should include (it's a work in progress, seeing what works).

**Comment by ch1bo** [comment]
Thanks for the review. Can you merge it or give me write permissions?

**Comment by JaredCorduan** [comment]
> Thanks for the review. Can you merge it or give me write permissions?

I'll do both :)

**Comment by dnadales** [comment]
> Any feedback on how to structure the content or how to align our weekly digest with the aim of this website welcome.

Likewise! If you have any suggestions on the structure and content of the existing reports let us know :heart:

**Pull request merged**
